import type { Question } from "@shared/schema";

export const questionBank: Question[] = [
  {
    id: "1",
    type: "mcq",
    question: "What does 'bonjour' mean?",
    correctAnswer: "Hello",
    options: ["Hello", "Goodbye", "Thank you", "Please"],
    hint: "This is a greeting you use when meeting someone.",
    explanation: "'Bonjour' means 'Hello' or 'Good day' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Greetings",
  },
  {
    id: "2",
    type: "mcq",
    question: "What does 'merci' mean?",
    correctAnswer: "Thank you",
    options: ["Please", "Thank you", "Sorry", "Yes"],
    hint: "You say this when someone helps you.",
    explanation: "'Merci' means 'Thank you' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Politeness",
  },
  {
    id: "3",
    type: "mcq",
    question: "What color is 'rouge'?",
    correctAnswer: "Red",
    options: ["Blue", "Green", "Red", "Yellow"],
    hint: "Think of a fire truck or a strawberry.",
    explanation: "'Rouge' means 'Red' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Colors",
  },
  {
    id: "4",
    type: "mcq",
    question: "What color is 'bleu'?",
    correctAnswer: "Blue",
    options: ["Blue", "Green", "Red", "Yellow"],
    hint: "Think of the sky or the ocean.",
    explanation: "'Bleu' means 'Blue' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Colors",
  },
  {
    id: "5",
    type: "mcq",
    question: "What does 'au revoir' mean?",
    correctAnswer: "Goodbye",
    options: ["Hello", "Goodbye", "See you later", "Good morning"],
    hint: "You say this when leaving.",
    explanation: "'Au revoir' means 'Goodbye' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Greetings",
  },
  {
    id: "6",
    type: "mcq",
    question: "What number is 'trois'?",
    correctAnswer: "3",
    options: ["1", "2", "3", "4"],
    hint: "It comes after deux (2).",
    explanation: "'Trois' means '3' (three) in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Numbers",
  },
  {
    id: "7",
    type: "mcq",
    question: "What number is 'cinq'?",
    correctAnswer: "5",
    options: ["4", "5", "6", "7"],
    hint: "Think of how many fingers on one hand.",
    explanation: "'Cinq' means '5' (five) in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Numbers",
  },
  {
    id: "8",
    type: "fill",
    question: "Complete: 'Je ____ (to be)' → I am",
    correctAnswer: "suis",
    hint: "The verb 'être' (to be) conjugated for 'je'.",
    explanation: "'Je suis' means 'I am'. The verb être becomes 'suis' for je.",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Verbs",
  },
  {
    id: "9",
    type: "fill",
    question: "Translate to French: 'cat'",
    correctAnswer: "chat",
    hint: "This fluffy pet says 'miaou' in French!",
    explanation: "'Chat' means 'cat' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Animals",
  },
  {
    id: "10",
    type: "fill",
    question: "Translate to French: 'dog'",
    correctAnswer: "chien",
    hint: "Man's best friend in French!",
    explanation: "'Chien' means 'dog' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Animals",
  },
  {
    id: "11",
    type: "conjugation",
    question: "Conjugate 'avoir' for 'tu' (you)",
    correctAnswer: "as",
    hint: "Remember: j'ai, tu __, il a...",
    explanation: "'Tu as' means 'you have'. Avoir (to have): tu as.",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Conjugation",
  },
  {
    id: "12",
    type: "conjugation",
    question: "Conjugate 'aller' for 'je' (I)",
    correctAnswer: "vais",
    hint: "Remember: aller → je vais, tu vas...",
    explanation: "'Je vais' means 'I go/am going'. Aller is irregular!",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Conjugation",
  },
  {
    id: "13",
    type: "mcq",
    question: "What does 'oui' mean?",
    correctAnswer: "Yes",
    options: ["Yes", "No", "Maybe", "Please"],
    hint: "The opposite of 'non'.",
    explanation: "'Oui' means 'Yes' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Basics",
  },
  {
    id: "14",
    type: "mcq",
    question: "What does 'non' mean?",
    correctAnswer: "No",
    options: ["Yes", "No", "Maybe", "Please"],
    hint: "The opposite of 'oui'.",
    explanation: "'Non' means 'No' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Basics",
  },
  {
    id: "15",
    type: "mcq",
    question: "What is 'un livre'?",
    correctAnswer: "A book",
    options: ["A book", "A pen", "A table", "A chair"],
    hint: "You read this!",
    explanation: "'Un livre' means 'a book' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Objects",
  },
  {
    id: "16",
    type: "mcq",
    question: "What color is 'vert'?",
    correctAnswer: "Green",
    options: ["Blue", "Green", "Red", "Yellow"],
    hint: "Think of grass or leaves.",
    explanation: "'Vert' means 'Green' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Colors",
  },
  {
    id: "17",
    type: "mcq",
    question: "What color is 'jaune'?",
    correctAnswer: "Yellow",
    options: ["Blue", "Green", "Red", "Yellow"],
    hint: "Think of the sun or a banana.",
    explanation: "'Jaune' means 'Yellow' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Colors",
  },
  {
    id: "18",
    type: "fill",
    question: "Translate to French: 'apple'",
    correctAnswer: "pomme",
    hint: "A round fruit, often red or green.",
    explanation: "'Pomme' means 'apple' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Food",
  },
  {
    id: "19",
    type: "fill",
    question: "Translate to French: 'water'",
    correctAnswer: "eau",
    hint: "You drink this to stay hydrated!",
    explanation: "'Eau' means 'water' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Food",
  },
  {
    id: "20",
    type: "mcq",
    question: "What does 's'il vous plaît' mean?",
    correctAnswer: "Please",
    options: ["Thank you", "Sorry", "Please", "Excuse me"],
    hint: "You use this word when asking for something politely.",
    explanation: "'S'il vous plaît' means 'Please' (formal) in French.",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Politeness",
  },
  {
    id: "21",
    type: "conjugation",
    question: "Conjugate 'être' for 'nous' (we)",
    correctAnswer: "sommes",
    hint: "Remember: je suis, tu es, il est, nous __...",
    explanation: "'Nous sommes' means 'we are'. Être (to be): nous sommes.",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Conjugation",
  },
  {
    id: "22",
    type: "mcq",
    question: "What number is 'dix'?",
    correctAnswer: "10",
    options: ["8", "9", "10", "11"],
    hint: "It's the number of fingers on both hands.",
    explanation: "'Dix' means '10' (ten) in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Numbers",
  },
  {
    id: "23",
    type: "mcq",
    question: "What is 'une maison'?",
    correctAnswer: "A house",
    options: ["A car", "A house", "A school", "A store"],
    hint: "You live in this building.",
    explanation: "'Une maison' means 'a house' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Places",
  },
  {
    id: "24",
    type: "fill",
    question: "Translate to French: 'bird'",
    correctAnswer: "oiseau",
    hint: "This animal can fly and has feathers.",
    explanation: "'Oiseau' means 'bird' in French.",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Animals",
  },
  {
    id: "25",
    type: "mcq",
    question: "What does 'je m'appelle' mean?",
    correctAnswer: "My name is",
    options: ["I am", "My name is", "I have", "I like"],
    hint: "You use this to introduce yourself.",
    explanation: "'Je m'appelle' means 'My name is' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Introductions",
  },
  {
    id: "26",
    type: "mcq",
    question: "What does 'j'aime' mean?",
    correctAnswer: "I like/love",
    options: ["I want", "I like/love", "I need", "I have"],
    hint: "Express your feelings about something you enjoy.",
    explanation: "'J'aime' means 'I like' or 'I love' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Expressions",
  },
  {
    id: "27",
    type: "conjugation",
    question: "Conjugate 'manger' for 'il/elle' (he/she)",
    correctAnswer: "mange",
    hint: "Regular -er verb: remove -er, add -e for il/elle.",
    explanation: "'Il/Elle mange' means 'He/She eats'. Regular -er verbs: il mange.",
    difficulty: 2,
    streak: 0,
    lastSeen: null,
    category: "Conjugation",
  },
  {
    id: "28",
    type: "mcq",
    question: "What is 'le soleil'?",
    correctAnswer: "The sun",
    options: ["The moon", "The sun", "The star", "The cloud"],
    hint: "It shines bright during the day.",
    explanation: "'Le soleil' means 'the sun' in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Nature",
  },
  {
    id: "29",
    type: "fill",
    question: "Translate to French: 'friend' (male)",
    correctAnswer: "ami",
    hint: "Someone you like to spend time with.",
    explanation: "'Ami' means 'friend' (male) in French. Female: amie.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "People",
  },
  {
    id: "30",
    type: "mcq",
    question: "What number is 'sept'?",
    correctAnswer: "7",
    options: ["5", "6", "7", "8"],
    hint: "Days of the week!",
    explanation: "'Sept' means '7' (seven) in French.",
    difficulty: 1,
    streak: 0,
    lastSeen: null,
    category: "Numbers",
  },
];

export function getQuestions(): Question[] {
  return questionBank;
}

export function getQuestionById(id: string): Question | undefined {
  return questionBank.find((q) => q.id === id);
}

export function selectNextQuestion(questionStates: Map<string, { streak: number; lastSeen: number | null }>): Question {
  const now = Date.now();
  
  const scoredQuestions = questionBank.map((q) => {
    const state = questionStates.get(q.id) || { streak: 0, lastSeen: null };
    
    let score = 100;
    
    score -= state.streak * 20;
    
    if (state.lastSeen) {
      const hoursSinceLastSeen = (now - state.lastSeen) / (1000 * 60 * 60);
      score += Math.min(hoursSinceLastSeen * 5, 50);
    } else {
      score += 30;
    }
    
    score += (3 - q.difficulty) * 10;
    
    score += Math.random() * 20;
    
    return { question: q, score };
  });
  
  scoredQuestions.sort((a, b) => b.score - a.score);
  
  return scoredQuestions[0].question;
}

export function checkAnswer(question: Question, answer: string): boolean {
  const normalizedAnswer = answer.toLowerCase().trim();
  const normalizedCorrect = question.correctAnswer.toLowerCase().trim();
  
  return normalizedAnswer === normalizedCorrect;
}
